const img = (id) => `https://images.unsplash.com/${id}?w=900&auto=format&fit=crop`;

export const RECETTES_DATA = [
    {
        id: 1,
        titre: "Riz sauce graine",
        description: "Un plat ivoirien très populaire à base de sauce graine, mijoté lentement pour libérer toute l'huile de palme.",
        ingredients: [
            "1 kg de graines de palme (ou 400 g de concentré de noix de palme)",
            "500 g de riz long grain",
            "600 g de viande de bœuf en morceaux",
            "150 g de poisson fumé",
            "2 oignons moyens",
            "2 tomates fraîches",
            "1 piment antillais entier",
            "2 gousses d'ail",
            "1 cube de bouillon",
            "1 c. à soupe de sel",
        ],
        etapes: [
            "Faire bouillir les graines de palme 25 min dans 2 L d'eau, jusqu'à ce qu'elles s'écrasent facilement.",
            "Piler les graines 10 min, puis extraire la sauce avec 1 L d'eau chaude et filtrer.",
            "Faire revenir la viande avec l'oignon émincé et l'ail 8 min, à feu vif.",
            "Verser la sauce graine sur la viande, ajouter tomates et cube, et laisser mijoter 30 min à découvert.",
            "Ajouter le poisson fumé et le piment entier, puis poursuivre 10 min à feu doux.",
            "Pendant ce temps, cuire le riz 18 min dans 1,5 fois son volume d'eau salée.",
            "Servir la sauce bien chaude sur le riz, en retirant le piment.",
        ],
        duree: 45,
        difficulte: "moyenne",
        image: img("photo-1665332195309-9d75071138f0"),
        categorie: "plats principaux",
        auteur: "le Carnet",
        favori: true,
    },
    {
        id: 2,
        titre: "Omelette rapide",
        description: "Une omelette simple et moelleuse, prête en dix minutes pour le petit déjeuner.",
        ingredients: [
            "4 œufs",
            "2 c. à soupe d'huile",
            "1/2 oignon finement émincé",
            "1 branche de persil ciselé",
            "1/2 c. à café de sel",
            "1 pincée de poivre",
        ],
        etapes: [
            "Casser les œufs dans un bol et les battre 1 min jusqu'à ce qu'ils moussent.",
            "Ajouter sel, poivre, oignon et persil, puis mélanger 30 s.",
            "Chauffer l'huile dans une poêle à feu moyen pendant 2 min.",
            "Verser les œufs et cuire 3 min sans remuer, jusqu'à ce que les bords prennent.",
            "Retourner l'omelette et poursuivre 2 min, puis servir aussitôt.",
        ],
        duree: 10,
        difficulte: "facile",
        image: img("photo-1510693206972-df098062cb71"),
        categorie: "petit déjeuner",
        auteur: "le Carnet",
        favori: false,
    },
    {
        id: 3,
        titre: "Attiéké poisson braisé",
        description: "Un classique ivoirien : semoule de manioc et poisson braisé, servis avec une sauce tomate-oignon relevée.",
        ingredients: [
            "600 g d'attiéké",
            "2 tilapias entiers (environ 400 g pièce)",
            "3 tomates mûres",
            "2 oignons",
            "1 piment frais",
            "3 c. à soupe d'huile",
            "2 citrons",
            "1 cube de bouillon",
            "1 c. à café de sel",
        ],
        etapes: [
            "Vider et rincer les poissons, puis les inciser sur chaque face.",
            "Assaisonner au citron, sel et cube, et laisser mariner 15 min.",
            "Braiser les poissons 20 min au total, en les retournant toutes les 10 min.",
            "Émincer oignons et tomates, puis les faire revenir 8 min à l'huile avec le piment.",
            "Réchauffer l'attiéké 5 min à la vapeur pour l'aérer.",
            "Servir le poisson sur l'attiéké, sauce à part.",
        ],
        duree: 35,
        difficulte: "facile",
        image: img("photo-1718942899999-b3da4177ee2a"),
        categorie: "plats principaux",
        auteur: "le Carnet",
        favori: true,
    },
    {
        id: 4,
        titre: "Poulet Yassa",
        description: "Poulet mariné au citron et fondu dans une montagne d'oignons caramélisés, originaire du Sénégal.",
        ingredients: [
            "1 poulet entier découpé (environ 1,4 kg)",
            "1 kg d'oignons émincés",
            "4 citrons (jus)",
            "2 c. à soupe de moutarde",
            "5 c. à soupe d'huile",
            "4 gousses d'ail",
            "2 feuilles de laurier",
            "1 cube de bouillon",
            "1/2 c. à café de poivre",
        ],
        etapes: [
            "Mélanger jus de citron, moutarde, ail, huile et poivre pour la marinade.",
            "Y plonger le poulet et réserver au frais 2 h minimum (4 h, c'est mieux).",
            "Égoutter les morceaux et les griller 15 min en les retournant à mi-cuisson.",
            "Faire fondre les oignons 20 min à feu doux, jusqu'à une belle couleur dorée.",
            "Ajouter la marinade filtrée et le laurier, puis laisser réduire 10 min.",
            "Remettre le poulet dans les oignons et mijoter 20 min à couvert.",
        ],
        duree: 50,
        difficulte: "moyenne",
        image: img("photo-1773620494293-e9e075dd48fd"),
        categorie: "plats principaux",
        auteur: "le Carnet",
        favori: false,
    },
    {
        id: 5,
        titre: "Garba",
        description: "La spécialité abidjanaise : attiéké chaud et thon frit croustillant, à manger avec les doigts.",
        ingredients: [
            "500 g d'attiéké",
            "400 g de thon frais en tranches épaisses",
            "500 ml d'huile de friture",
            "2 oignons rouges",
            "2 tomates",
            "2 piments frais",
            "1 cube de bouillon",
            "1 c. à café de sel",
        ],
        etapes: [
            "Découper le thon en tranches de 2 cm et l'assaisonner sel-cube 5 min.",
            "Chauffer l'huile 5 min, jusqu'à ce qu'un morceau de pain y dore en 30 s.",
            "Frire le thon 6 min par face, jusqu'à une croûte bien dorée, puis égoutter.",
            "Émincer finement oignons, tomates et piments pendant la friture.",
            "Réchauffer l'attiéké 4 min à la vapeur.",
            "Dresser l'attiéké, poser le thon dessus et couvrir de légumes.",
        ],
        duree: 15,
        difficulte: "facile",
        image: img("photo-1786997089873-e4c02377bd3d"),
        categorie: "snack",
        auteur: "le Carnet",
        favori: true,
    },
    {
        id: 6,
        titre: "Sauce Claire à la Viande",
        description: "Une sauce légère aux légumes fondants, mijotée longuement et servie avec du riz blanc.",
        ingredients: [
            "800 g de viande de bœuf en cubes",
            "3 aubergines africaines",
            "2 carottes",
            "2 oignons",
            "3 c. à soupe de concentré de tomate",
            "2 piments",
            "2 cubes de bouillon",
            "2 c. à soupe d'huile",
            "1,5 L d'eau",
        ],
        etapes: [
            "Faire bouillir la viande 25 min avec un oignon et un cube, dans 1,5 L d'eau.",
            "Couper aubergines et carottes en dés pendant la cuisson.",
            "Ajouter les légumes au bouillon et cuire 15 min à feu moyen.",
            "Délayer le concentré de tomate dans une louche de bouillon, puis l'incorporer.",
            "Ajouter les piments entiers et laisser mijoter 30 min à découvert pour réduire.",
            "Rectifier le sel et servir avec du riz blanc.",
        ],
        duree: 60,
        difficulte: "difficile",
        image: img("photo-1763048443535-1243379234e2"),
        categorie: "plats principaux",
        auteur: "le Carnet",
        favori: false,
    },
];
